apiVersion: apps/v1
kind: Deployment
metadata:
  name: tictac-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tictac
  template:
    metadata:
      labels:
        app: tictac
    spec:
      containers:
      - name: tictac
        image: 116981802760.dkr.ecr.us-east-1.amazonaws.com/tictac:sha-b46b896
        ports:
        - containerPort: 80
