apiVersion: v1
kind: Service
metadata:
  name: tic-tac-toe
  namespace: default  # Ensure this matches your deployment namespace
  labels:
    app: tic-tac-toe
spec:
  type: LoadBalancer
  selector:
    app: tic-tac-toe
  ports:
    - name: http
      port: 80
      targetPort: 3000  # Change this if your app is running on a different port
      protocol: TCP
